all:
	pyuic4 main_win.ui -o MainWin.py
	pyuic4 MainWindow.ui -o MainWindow.py
	pyuic4 class_dialog.ui -o ClassDialog.py
	pyuic4 regatta_dialog.ui -o RegattaDialog.py
	pyuic4 legenda_dialog.ui -o LegendaDialog.py

clean:
	rm -f *.old
	rm -f *.pyc
	
