all:
	pyuic4 gui/main_win.ui -o modules/MainWin.py
	pyuic4 gui/MainWindow.ui -o modules/MainWindow.py
	pyuic4 gui/class_dialog.ui -o modules/ClassDialog.py
	pyuic4 gui/regatta_dialog.ui -o modules/RegattaDialog.py
	pyuic4 gui/legenda_dialog.ui -o modules/LegendaDialog.py

clean:
	rm -f *.old
	rm -f *.pyc
	
